import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  // Change master to your branch name to pull the schema from your branch
  schema: "http://localhost:4000/graphql",
  documents: "src/graphql/**/*.graphql",
  generates: {
    "src/graphql/generated/graphqlTypes.tsx": {
      hooks: {
        afterOneFileWrite: ["prettier --write"],
      },
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-react-apollo",
        {
          add: {
            content: [
              "/**",
              "*",
              "* THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!",
              "*",
              "* instead, edit one of the `.graphql` files in this project and run",
              "*",
              "* pnpm generate-gql",
              "*",
              "* for this file to be re-created",
              "*/",
            ].join("\n"),
          },
        },
      ],
      config: {
        avoidOptionals: {
          field: true,
          object: true,
          inputValue: false,
          defaultValue: true,
        },
        scalars: {
          Byte: "number",
          Long: "number",
          Short: "number",
          UnsignedShort: "number",
        },
        maybeValue: "T",
        withHooks: true,
        preResolveTypes: true,
        namingConvention: {
          transformUnderscore: true,
          enumValues: "upper-case#upperCase",
        },
        addDocBlocks: false,
        dedupeOperationSuffix: true,
        exportFragmentSpreadSubTypes: true,
      },
    },
    "src/graphql/generated/graphqlMocks.tsx": {
      plugins: [
        {
          "typescript-mock-data": {
            addTypename: true,
            typesFile: "./graphqlTypes.ts",
            enumValues: "upper-case#upperCase",
            scalars: {
              DateTime: "new Date().toString()",
              Byte: "1234",
              Long: "1234",
              Short: "1234",
              UnsignedShort: "1234",
            },
            listElementCount: 0,
          },
        },
        {
          add: {
            content: [
              "/* eslint-disable @typescript-eslint/no-unused-vars */",
              "/**",
              "*",
              "* THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!",
              "*",
              "* instead, edit one of the `.graphql` files in this project and run",
              "*",
              "* pnpm generate-gql",
              "*",
              "* for this file to be re-created",
              "*/",
            ].join("\n"),
          },
        },
      ],
    },
  },
};
export default config;
