// module.exports = {
//   parser: "@typescript-eslint/parser",
//   extends: [
//     "eslint:recommended",
//     "plugin:react/recommended",
//     "plugin:@typescript-eslint/recommended",
//     "airbnb",
//   ],
//   parserOptions: {
//     ecmaVersion: 2020,
//     sourceType: "module",
//   },
//   rules: {
//     "@typescript-eslint/ban-ts-comment": "off",
//     "@typescript-eslint/ban-types": "off",
//     "@typescript-eslint/naming-convention": "off",
//     "@typescript-eslint/no-explicit-any": "off",
//     "@typescript-eslint/no-floating-promises": "off",
//     "@typescript-eslint/no-redundant-type-constituents": "off",
//     "@typescript-eslint/no-non-null-assertion": "off",
//     "@typescript-eslint/no-unsafe-argument": "off",
//     "@typescript-eslint/no-unsafe-assignment": "off",
//     "@typescript-eslint/no-unsafe-call": "off",
//     "@typescript-eslint/no-unsafe-enum-comparison": "off",
//     "@typescript-eslint/no-unsafe-member-access": "off",
//     "@typescript-eslint/no-unsafe-return": "off",
//     "@typescript-eslint/no-use-before-define": "off",
//     "@typescript-eslint/require-await": "off",
//     "@typescript-eslint/restrict-template-expressions": "off",
//     "@typescript-eslint/unbound-method": "off",
//     "eslint-comments/disable-enable-pair": "off",
//     "eslint-comments/require-description": "off",
//     "no-case-declarations": "off",
//     "no-prototype-builtins": "off",
//     "no-useless-catch": "off",
//     "no-empty-pattern": "off",
//     "react/function-component-definition": "off",
//     "react/jsx-key": "off",
//     "react/jsx-no-bind": "off",
//     "jsx-a11y/click-events-have-key-events": "off",
//     "jsx-a11y/no-static-element-interactions": "off",
//   },
// };
