services:
  db:
    build:
      context: ./apps/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: race_hub_db
    networks:
      - racehub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d race_hub_db -h localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  backend:
    build:
      context: ./apps/backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/race_hub_db
      REDIS_URL: redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
    networks:
      - racehub-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - racehub-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  racehub-network:
    driver: bridge
